[package]
name = "ascplayer"
version = "0.1.0"
edition = "2024"

[dependencies]
A2VConverter = "0.1.1"
crossterm = ">=0.28.1"
ffmpeg-next = ">=7.1.0"
image = ">=0.25.5"
rodio = ">=0.20.1"
spin_sleep = ">=1.3.0"

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
lto = "thin"
